apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw24-python-random-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw24-python-random
  template:
    metadata:
      labels:
        app: hw24-python-random
    spec:
      containers:
      - name: hw24-python-random
        image: alexdevops05/hw24-python-random:2.0
        ports:
        - containerPort: 8082